title: <strong>Alexandre B A Villares</strong>

site_name: Alexandre B A Villares @ lugaralgum

# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Alexandre B. A. Villares

# Your name, as you want it to appear underneath each post and in the footer
author: Alexandre Villares

# Your email if you want it to be linked on the contact page
# author_email: 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://abav.lugaralgum.com

# logo: /assets/logo.png

# google_analytics:
